# Generated by Django 6.1.1 on 2026-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
