# Generated by Django 6.1.1 on 2026-09-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_financialreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cost_of_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_statement', to='companies.financialreport')),
            ],
        ),
    ]
