# Generated by Django 6.1.1 on 2026-09-29 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_incomestatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_and_equivalents', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='companies.financialreport')),
            ],
        ),
    ]
