# Generated by Django 6.1.1 on 2026-09-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_balancesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investing_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('financing_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capital_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_statement', to='companies.financialreport')),
            ],
        ),
    ]
