# Generated by Django 6.1.1 on 2026-10-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_cashflowstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('FY', 'Full Year')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='companies.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'year', 'period'), name='unique_company_dividend_period')],
            },
        ),
    ]
