# Generated by Django 6.1.1 on 2026-10-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_group', models.CharField(max_length=255)),
                ('recommendation', models.CharField(choices=[('BUY', 'BUY'), ('HOLD', 'HOLD'), ('SELL', 'SELL')], max_length=4)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_forecasts', to='companies.company')),
            ],
        ),
    ]
